version: '3'

services:
  docker-regen:
    container_name: regen
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - MONIKER=Regen-Node
      - CHAIN_ID=regen-1
      - VERSION=v1.0.0
    restart: always
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26658:26658"
      - "1317:1317" # for rest-server
    volumes:
      - regen-data:/.regen
volumes:
  regen-data:
