version: '3'

services:
  docker-regen:
    container_name: regen
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - MONIKER=Regen-Node
      - CHAIN_ID=regen-test-1001
      - GENESIS_URL=https://raw.githubusercontent.com/regen-network/testnets/master/regen-test-1001/genesis.json
      - VERSION=v0.4.1
    restart: always
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26658:26658"
      - "1317:1317" # for rest-server
    volumes:
      - data:/.regen
volumes:
  data:
